### ISSUE TITLE
Missing GPL file

### ISSUE THREAD

**Issue by willysr** [linuxmint/pia-manager#6]
Running pia-manager from command line showed a missing GPL file

```
[Errno 2] No such file or directory: '/usr/share/common-licenses/GPL'
<class 'FileNotFoundError'>
```

**Comment by theel0ja** [comment]
Also, the pia-manager seems to be licensed with [LGPL-3](https://github.com/linuxmint/pia-manager/blob/master/COPYING), so the file should be `/usr/share/common-licenses/LGPL-3`.
