### ISSUE TITLE
PIA Manager & Repository

### ISSUE THREAD

**Issue by callagg2** [linuxmint/pia-manager#8]
Can we add the pia-manager to the Software Manager?

I know here (http://blog.linuxmint.com/?p=3178) we said it would be added to the repositories in time
but I can't find it in mintinstall 7.7.5 (Cinnamon 3.4.1).

The version on the blog page, while easy to set up, could be user friendly for quickly changing between the different VPNs available from PIA. 

It would also be nice to be able to select an option to automatically turn it on at boot time.

**Comment by callagg2** [comment]
The Pia-Manager is now in the Software Manager for LM 18.2 (mintinstall 7.7.7)
However, the correct green icon is not appearing beside the name in the search results.
If you then go to the installation page, the green icon does not appear until the application is installed.
Not sure if this is a feature or a bug.

**Comment by clefebvre** [comment]
It's in the repositories by default now. The lack of icon depends on the icon theme, we'll check that in mint-x and mint-y.
